//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        internal static System.Drawing.Icon eye
        {
            get
            {
                object obj = ResourceManager.GetObject("eye", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon hide
        {
            get
            {
                object obj = ResourceManager.GetObject("hide", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon admin
        {
            get
            {
                object obj = ResourceManager.GetObject("admin", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon license
        {
            get
            {
                object obj = ResourceManager.GetObject("license", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon customer
        {
            get
            {
                object obj = ResourceManager.GetObject("customer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon program
        {
            get
            {
                object obj = ResourceManager.GetObject("program", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon programLicense
        {
            get
            {
                object obj = ResourceManager.GetObject("programLicense", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon update
        {
            get
            {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon version
        {
            get
            {
                object obj = ResourceManager.GetObject("version", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon menu
        {
            get
            {
                object obj = ResourceManager.GetObject("menu", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon user
        {
            get
            {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon logout
        {
            get
            {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon add
        {
            get
            {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon delete
        {
            get
            {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon edit
        {
            get
            {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon toggle
        {
            get
            {
                object obj = ResourceManager.GetObject("toggle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon key
        {
            get
            {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Icon adminUser
        {
            get
            {
                object obj = ResourceManager.GetObject("adminUser", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }



        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
